[2022-02-08 03:20:27,017] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_print.task_1_data_file_cleanup manual__2022-02-08T03:19:38.055974+00:00 [queued]>
[2022-02-08 03:20:27,255] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: test_print.task_1_data_file_cleanup manual__2022-02-08T03:19:38.055974+00:00 [queued]>
[2022-02-08 03:20:27,255] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-08 03:20:27,255] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-02-08 03:20:27,255] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-08 03:20:27,527] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): task_1_data_file_cleanup> on 2022-02-08 03:19:38.055974+00:00
[2022-02-08 03:20:27,531] {standard_task_runner.py:52} INFO - Started process 22074 to run task
[2022-02-08 03:20:27,537] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test_print', 'task_1_data_file_cleanup', 'manual__2022-02-08T03:19:38.055974+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp3crb1aac', '--error-file', '/tmp/tmpeg6hibm1']
[2022-02-08 03:20:27,538] {standard_task_runner.py:77} INFO - Job 31: Subtask task_1_data_file_cleanup
[2022-02-08 03:20:28,447] {logging_mixin.py:109} INFO - Running <TaskInstance: test_print.task_1_data_file_cleanup manual__2022-02-08T03:19:38.055974+00:00 [running]> on host workspace-1-v1-5d989644d9-ns2w7
[2022-02-08 03:20:29,137] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/xcom.py:323 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-02-08 03:20:29,264] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/renderedtifields.py:126 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-02-08 03:20:29,434] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/renderedtifields.py:162 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2022-02-08 03:20:29,444] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/renderedtifields.py:159 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-02-08 03:20:29,659] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akj00173@gmail.com
AIRFLOW_CTX_DAG_OWNER=someone
AIRFLOW_CTX_DAG_ID=test_print
AIRFLOW_CTX_TASK_ID=task_1_data_file_cleanup
AIRFLOW_CTX_EXECUTION_DATE=2022-02-08T03:19:38.055974+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-08T03:19:38.055974+00:00
[2022-02-08 03:20:29,661] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-08 03:20:29,662] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /workspace/tracker/code/track_chicken_date_gpu.py "/workspace/nas-data/Animal/chicken_video/"$(date -d "yesterday" +%Y%m%d)']
[2022-02-08 03:20:29,694] {subprocess.py:85} INFO - Output:
[2022-02-08 03:20:32,013] {subprocess.py:89} INFO - Traceback (most recent call last):
[2022-02-08 03:20:32,013] {subprocess.py:89} INFO -   File "/workspace/tracker/code/track_chicken_date_gpu.py", line 94, in <module>
[2022-02-08 03:20:32,013] {subprocess.py:89} INFO -     LABELS = open(labelsPath).read().strip().split("\n")
[2022-02-08 03:20:32,013] {subprocess.py:89} INFO - FileNotFoundError: [Errno 2] No such file or directory: './yolo/coco.names'
[2022-02-08 03:20:32,680] {subprocess.py:93} INFO - Command exited with return code 1
[2022-02-08 03:20:32,880] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-02-08 03:20:32,950] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=test_print, task_id=task_1_data_file_cleanup, execution_date=20220208T031938, start_date=20220208T032027, end_date=20220208T032032
[2022-02-08 03:20:32,955] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dagrun.py:466 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
[2022-02-08 03:20:33,121] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-02-08 03:20:33,123] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-02-08 03:20:33,124] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-02-08 03:20:33,126] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-02-08 03:20:33,127] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-02-08 03:20:33,128] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-02-08 03:20:33,130] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-02-08 03:20:33,130] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-02-08 03:20:33,131] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-02-08 03:20:33,131] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-02-08 03:20:33,132] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-02-08 03:20:33,133] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-02-08 03:20:33,215] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/utils/email.py:102 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2022-02-08 03:20:33,215] {email.py:208} INFO - Email alerting: attempt 1
[2022-02-08 03:20:33,826] {email.py:220} INFO - Sent an alert email to ['akj00173@gmail.com']
[2022-02-08 03:20:35,290] {standard_task_runner.py:89} ERROR - Failed to execute job 31 for task task_1_data_file_cleanup
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/conda/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/conda/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/conda/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/conda/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/conda/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/bash.py", line 187, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-02-08 03:20:35,309] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-08 03:20:36,091] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-08 03:20:36,095] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:1076 SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
[2022-02-08 03:20:36,096] {logging_mixin.py:109} WARNING - /opt/conda/lib/python3.8/site-packages/airflow/models/dag.py:1076 SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
